---
- name: Create new Linux user with SSH key and shell
  hosts: all
  become: yes

  tasks:
    - name: Ensure the user exists
      ansible.builtin.user:
        name: "{{ new_user }}"
        shell: "{{ user_shell }}"
        create_home: yes
        password: "{{ user_passwd | password_hash('sha512') }}"
        update_password: on_create # Only set password on user creation
        state: present

    - name: Ensure .ssh directory exists
      ansible.builtin.file:
        path: "/home/{{ username }}/.ssh"
        state: directory
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0700'

    - name: Add authorized SSH key
      ansible.builtin.copy:
        dest: "/home/{{ username }}/.ssh/authorized_keys"
        content: "{{ user_ssh_key }}\n"
        owner: "{{ username }}"
        group: "{{ username }}"
        mode: '0600'

    - name: Ensure shell is correctly set
      ansible.builtin.user:
        name: "{{ username }}"
        shell: "{{ user_shell }}"
