---
- name: Update Debian and Arch Linux hosts
  hosts: all
  become: yes
  gather_facts: yes
  serial: 1            # update one host at a time

  tasks:
    - name: Update package cache and upgrade system (Debian/Ubuntu)
      ansible.builtin.apt:
        update_cache: yes
        upgrade: yes
      when: ansible_facts['os_family'] == "Debian"

    - name: Update package database (Arch Linux)
      ansible.builtin.pacman:
        update_cache: yes
      when: ansible_facts['os_family'] == "Archlinux"

    - name: Perform full system upgrade (Arch Linux) and disable-sandbox
      ansible.builtin.command: pacman -Syu --noconfirm --disable-sandbox
      when: ansible_facts['os_family'] == "Archlinux"
      register: pacman_upgrade
      changed_when: "'upgraded' in pacman_upgrade.stdout or 'installed' in pacman_upgrade.stdout"

    - name: Clean up unused packages (Debian/Ubuntu)
      ansible.builtin.apt:
        autoremove: yes
        autoclean: yes
      when: ansible_facts['os_family'] == "Debian"